# Generated by Django 5.1 on 2024-09-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='credits',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
